repos:
    # Check that the commit message adheres to the Angular convention (this is needed so that Semantic Release works)
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.27.1
      hooks:
          - id: commitizen
            stages: [commit-msg]

    # Fixes the spaces
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
